### PR TITLE
Update for v2.0.0

### PR DESCRIPTION
**Pull request by adrianeboyd**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
@conda-forge/catalogue this looks ready.

@adrianeboyd are you interested in becoming a maintainer? If so please add yourself. If the maintainers don't get back to you please let me (or someone else on core) know.

**Comment by adrianeboyd** [comment]
@CJ-Wright: Thanks for the heads up, this must have fallen through the cracks. I'll ask Ines to take a look again.

What's the best way to add someone to a feedstock repo? There's the list in the README and the "please update team" command, but I couldn't quite figure out the intended usage?

**Comment by CJ-Wright** [comment]
Add yourself to the `meta.yaml` under the maintainers section.

**Pull request merged**
